// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Download: typeof import('./src/pages/download.vue')['default']
    FilePreview: typeof import('./src/components/FilePreview.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('./src/components/RouterLink.vue')['default']
    Upload: typeof import('./src/pages/upload.vue')['default']
  }

}
