[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  base="frontend"
  publish = "dist"
  command = "npx pnpm --filter frontend i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

