// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Download: typeof import('./pages/download.vue')['default']
    DownloadFilePreview: typeof import('./components/DownloadFilePreview.vue')['default']
    FilePreview: typeof import('./components/UploadFilePreview.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RouterLink: typeof import('./components/RouterLink.vue')['default']
    Upload: typeof import('./pages/upload.vue')['default']
    UploadFilePreview: typeof import('./components/UploadFilePreview.vue')['default']
  }

}
