// Generated by Wrangler on Sat Jun 01 2024 23:19:58 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types --env preview`

interface Env {
	NODE_VERSION: "20";
	PNPM_VERSION: "9";
	BUCKET: R2Bucket;
	DB: D1Database;
}
