// Generated by Wrangler on Tue Jun 04 2024 17:31:12 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types --env preview`

interface Env {
	NODE_VERSION: "20";
	PNPM_VERSION: "9";
	FRONTEND_URL: "https://ez-share.pages.dev";
	BUCKET: R2Bucket;
	DB: D1Database;
}
