name: Deploy Firebase Rules DEV

on:
  push:
    branches: [dev]
    paths:
      - 'firestore.indexes.json'
      - 'firestore.rules'
      - 'storage.rules'

jobs:
  deploy_rules:
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Deploy Rules
        run: npx firebase-tools deploy --only storage,firestore --project dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
